### ISSUE TITLE
Deployment checklist

### ISSUE THREAD

**Issue by michalk8** [theislab/squidpy#258]
Deployment checklist:
- [x] merge #220 (ImageContainer)
- [x] merge #218 (docs style)
- [x] merge #206 (change README)
- [x] add `all` extra requirement
- [x] verify that tests pass on Python 3.7
- [ ] finish the checklist for `squidpy_tutorials` and open up the repo
- [x] verify that after the above, we can clone the tutorials from github (in `docs/source/conf.py`, set `raise_exc = True`)
- [x] determine which requirements should/should not be extra (`astropy`, `esda`, `libpysal` will be in `all`)
- [x] pin minimal requirements version
- [x] determine the fate of `squidpy.im.read_seqfish` - either polish, make private (i.e. not export) or remove
- [x] use valid __email__ in `squidpy/__init__.py` (because of PyPI will only accept valid email addresses) - alt is to use one different in `__email__` and different supplied in `setup.py`, but I'm against
- [x] run `tox -e check-docs` (for spelling/link checking)
- [x] in `setup.py`, change development status to 5, stable
- [x] run `tox -e readme` to verify README.rst will correctly render
- [x] populate keywords in `setup.py` - https://github.com/theislab/squidpy/blob/master/setup.py#L63
- [x] verify that badge links/links in `setup.py` are (or will be, once the endpoints exist) are correct
- [x] add repository secret named `PYPI_TOKEN` - it should contain the token for `__token__` user on PyPI
- [x] remove `notebooks` directory and optional (highly recommended) - purge ipynb files from git history - notebooks dir is removed in #266, purge should happen after the PR is merged
- [x] set up ISSUE template, optionally PR template as well
- [x] (optional) add some description to all the valid features in `FeatureMixin`
- [x] change `fail_on_warning` in `.readthedocs.yml` (I expect there will be some warnings)
- [x] remove/add stuff related to the fact we are a private repo:
  - in `ci.yml`:
    - enable `tox -e check-docs` on the CI (if it doesn't give too much troubles)
    - enable different Python versions (at least 3.7), maybe enable macOS, if plotting is fine
    - remove CODECOV_TOKEN (also from repo secrets)
  - in `tox.ini`:
    - remove SQUIDPY_NOTEBOOKS_TOKEN (also from repo secrets)
    - uncomment `check-docs` in [test]
- [x] add more badges if desired (i.e. pre-preprint, num. of downloads) - download badge has been added

Afterwards, the deployment steps are as follows:
- 1. run `git config --global push.followTags true`  # needs to be done only once
- 2. run `pip install bump2version`  # needs to be done only once
- 3. run `bump2version major`  # creates a commit like 0.0.0 -> 1.0.0 and a new tag v1.0.0
- 4. run `git push`

Then, we just need to wait unti tests on the CI pass.
